services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
    networks:
      - symfony_net

  web:
    image: nginx:1.25
    container_name: symfony_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony_net

  redis:
    image: redis:7
    container_name: symfony_redis
    ports:
      - "6379:6379"
    networks:
      - symfony_net

networks:
  symfony_net:
    driver: bridge

